### ISSUE TITLE
Issue:000

### ISSUE THREAD

**Issue by mrprofessor** [kirimaks/http-convey#1]
Can you add some code for `https`filtering..and it only filters `url`, not web contents.

**Comment by kirimaks** [comment]
Yeah can filter only http urls now. I start to make it but a bit forget about it. I thought about analyse full page when it's downloaded (for example make list of images that must be filtered, and change those paths inside page). Then it will doesn't matter about protocol and so on. But need to implement https, because now https works just at a bridge (proxy has encrypted data). Ok I will think about it.
If you have any ideas, tell me please.

**Comment by mrprofessor** [comment]
Sorry...I am not an expert.Using your coding style for my final year project(To block adult sites).Still i have a sluggish idea..first we can scrap the whole web page and then search for any offensive text and if found...Filtered.
And if there are any ready-made content filters(python) let me know..I only have five more days left.

**Comment by kirimaks** [comment]
Ok, I will play with lxml in free time. Now I can't offer something, good luck.
